# Generated by Django 4.2.3 on 2023-08-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
