# Generated by Django 4.2.3 on 2023-08-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projects_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='content',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='views',
        ),
        migrations.AddField(
            model_name='projects',
            name='last_commits',
            field=models.TextField(default='----'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='rdme',
            field=models.URLField(null=True),
        ),
    ]
