# Generated by Django 4.2.3 on 2023-08-23 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_content_projects_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='commits',
            field=models.IntegerField(default=0),
        ),
    ]
