# Generated by Django 4.2.3 on 2023-08-23 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_projects_commits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='rdme',
        ),
    ]
