# Generated by Django 4.2.3 on 2023-08-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_projects_rdme'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='branches',
            field=models.IntegerField(default=0),
        ),
    ]
