# Generated by Django 4.2.3 on 2023-07-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('author', models.TextField(default='User')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('views', models.IntegerField()),
                ('comments', models.IntegerField()),
            ],
        ),
    ]
