# Generated by Django 4.2.3 on 2023-07-31 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_poststhumbs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poststhumbs',
            name='combined_key',
        ),
    ]
