# Generated by Django 4.2.3 on 2023-08-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_desc',
            field=models.TextField(default='Default profile description', max_length=250),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user_rank',
            field=models.CharField(choices=[('newbie', 'Newbie'), ('junior', 'Junior'), ('member', 'Member'), ('seniormember', 'SeniorMember'), ('veteran', 'Veteran'), ('expert', 'Expert'), ('guru', 'Guru'), ('moderator', 'Moderator'), ('admin', 'Administrator')], default='newbie', max_length=20),
        ),
    ]
