# Generated by Django 4.2.3 on 2023-08-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_myuser_user_desc_myuser_user_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_rank',
            field=models.CharField(choices=[('Newbie', 'Newbie'), ('Junior', 'Junior'), ('Member', 'Member'), ('SeniorMember', 'SeniorMember'), ('Veteran', 'Veteran'), ('Expert', 'Expert'), ('Guru', 'Guru'), ('Moderator', 'Moderator'), ('Administrator', 'Administrator')], default='newbie', max_length=20),
        ),
    ]
