# Generated by Django 4.2.3 on 2023-08-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_myuser_user_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='user_desc',
            field=models.TextField(default='default_profile_pic.png', max_length=250),
        ),
    ]
