# Generated by Django 4.2.3 on 2023-08-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_myuser_user_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/users_prof_img/'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_desc',
            field=models.TextField(default='Default profile description', max_length=250),
        ),
    ]
