# Generated by Django 4.2.3 on 2023-08-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_myuser_profile_pic_alter_myuser_user_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/users_prof_img/default_profile_pic.png', null=True, upload_to='images/users_prof_img/'),
        ),
    ]
