# Generated by Django 4.2.3 on 2023-08-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_myuser_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_pic',
            field=models.ImageField(blank=True, default='users_prof/default_profile_pic.png', null=True, upload_to='users_prof/'),
        ),
    ]
