# Generated by Django 4.2.3 on 2023-07-11 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='posts_comments',
            table='Posts_comments',
        ),
    ]
